Feature/152638438 registration flow
OpenConext/Stepup-gssp-bundle pull request #2
Opened 2017-11-15 08:57 UTC by epinxteren

2017-11-20 18:23 UTC, epinxteren commented on src/Features/Fixture/AuthnRequest_registration.xml
> +</samlp:AuthnRequest>
Can be deleted

2017-11-22 08:47 UTC, MKodde requested changes

2017-11-22 08:47 UTC, MKodde commented on src/Controller/IdentityController.php
> +    public function renderSamlResponse($view, SAML2_Response $response)
No need to make this method publicly available, right?

2017-11-22 08:47 UTC, MKodde commented on src/Service/ConfigurationContainer.php
> +//        Assertion::keyExists($configuration, 'registration_route');
Forgot to remove these comments?

2017-11-22 08:47 UTC, MKodde commented on src/Saml/ResponseBuilder.php
> +            SAML2_Const::STATUS_NO_AUTHN_CONTEXT,           // insufficient Loa or Loa cannot be met
Do you need to test for a valid Authn Context? In the case of Gateway the required Loa is loaded from the Authn Context. In this context this seems irrelevant. Please verify this with an expert ;)

2017-11-22 08:47 UTC, MKodde commented on README.md
> +assetic:
I thought you would have chosen the more modern [Encore](https://symfony.com/blog/introducing-webpack-encore-for-asset-management). (webpack based) frontend asset management solution. Im totaly fine with the Assetic solution, but you might want to reconsider.

2017-11-22 08:47 UTC, MKodde commented on README.md
> +The purpose of the development environment is only for running the different test and metric tools only.
Suggestion to remove the last 'only' from this sentence.

2017-11-22 08:47 UTC, MKodde commented on src/Controller/IdentityController.php
> +    public function ssoReturnAction()
Consider describing the intent of this controller action. This comment goes for the other actions as well.

2017-11-22 08:47 UTC, MKodde commented on tests/TestUnitTest.php
> +namespace Tests\Surfnet\GsspBundle;
This test can be removed as discussed IRL.

2017-11-22 08:47 UTC, MKodde commented on src/Features/Context/GsspContext.php
> +        $request->setProtocolBinding(SAML2_Const::BINDING_HTTP_POST);
Using the `SAML2_Const::BINDING_HTTP_REDIRECT` protocol binding is more in line with how this service will be used.

2017-11-22 16:08 UTC, merged